config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'personal_informations#edit'
  resources :users do
    resource :personal_information, only: [:show, :edit, :update, :create]  # Singular resource as each user has one personal information
  end
  resources :warm_ups
  resources :personal_informations
  resources :kinesiologist_details
  resources :personal_trainer_details
  resources :trainings

  resources :videos  # Agregar esta línea para los videos

end

app/models/training.rb
class Training < ApplicationRecord
    belongs_to :user
    has_many :warm_ups
  
    validates :exercise, presence: true
    validates :day, presence: true
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: %i[show edit update destroy]

  # GET /trainings
  def index
    @trainings = current_user.trainings
  end

  # GET /trainings/1
  def show
    @training = Training.find(params[:id])
  end
  

  # GET /trainings/new
  def new
    @training = Training.new
  end

  # GET /trainings/1/edit
  def edit
    @training = Training.find(params[:id])
  end
  

  # POST /trainings
  def create
    @training = current_user.trainings.build(training_params)
    if @training.save
      redirect_to @training, notice: 'Training was successfully created.'
    else
      flash.now[:alert] = @training.errors.full_messages.to_sentence
      render :new
    end
  end

  # PATCH/PUT /trainings/1
  def update
    if @training.update(training_params)
      redirect_to @training, notice: 'Training was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /trainings/1
  def destroy
    @training.destroy
    redirect_to trainings_url, notice: 'Training was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_training
    @training = Training.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def training_params
    params.require(:training).permit(:exercise, :classification, :day)
  end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= form_with(model: training, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :exercise, "Ejercicio", class: "form-label" %>
      <%= form.text_field :exercise, class: "form-control" %>
    </div>
  
    <div class="mb-3">
      <%= form.label :classification, "Descripción", class: "form-label" %>
      <%= form.text_field :classification, class: "form-control" %>
    </div>
  
    <div class="mb-3">
      <%= form.label :day, "Día", class: "form-label" %>
      <%= form.select :day, options_for_select(['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']), {}, class: "form-select" %>
    </div>
  
    <div class="actions">
      <%= form.submit "Guardar Entrenamiento", class: "btn btn-primary" %>
    </div>
  <% end %>
  

app/views/trainings/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h3 class="card-title mb-0">Editar Entrenamiento</h3>
        </div>
        <div class="card-body">
          <%= render 'form', training: @training %>
        </div>
        <div class="card-footer">
            <%= link_to 'Volver', training_path(@training), class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trainings/index.html.erb
<div class="container mt-5">
<h1 class="fancy-title font-italic">Mis entrenamientos</h1>
<%= link_to 'Crear Entrenamiento', new_training_path, class: 'btn btn-primary' %>
<% if @trainings.any? %>
  <p> </p>

    <div class="row">
      <% @trainings.each do |training| %>
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-header bg-warning text-dark">
              <h5><%= training.exercise %></h5>
            </div>
            <div class="card-body">
              <p class="card-text"><strong>Dia:</strong> <%= training.day %></p>
              <div class="btn-group" role="group">
                <%= link_to 'Ver', training_path(training), class: 'btn btn-primary' %>
                <%= link_to 'Editar', edit_training_path(training), class: 'btn btn-secondary' %>
                <%= link_to 'Eliminar', training, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>No hay entrenamientos disponibles.</p>
  <% end %>
</div>

app/views/trainings/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h3>Nuevo Entrenamiento</h3>
        </div>
        <div class="card-body">
          <%= render 'form', training: @training %>
          <%= link_to 'Volver', trainings_path, class: 'btn btn-secondary mt-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trainings/show.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-header bg-primary text-white">
      <h1 class="fancy-title font-italic">Detalles del Entrenamiento</h1>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @training.exercise %></h5>
      <p class="card-text"><strong>Día:</strong> <%= @training.day %></p>
      <h5 class="card-subtitle mb-2 text-muted">Descripción:</h5>
      <p class="card-text"><%= @training.classification %></p>
      <h5 class="card-subtitle mb-2 text-muted">Calentamientos:</h5>
      <% @training.warm_ups.each do |warm_up| %>
        <div class="card mb-3">
          <div class="card-header bg-warning">
            <h5 class="card-title"><%= warm_up.exercise %></h5>
          </div>
          <div class="card-body">
            <div class="d-grid">
              <%= link_to 'Ver Calentamiento', warm_up_path(warm_up), class: 'btn btn-outline-primary btn-sm' %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="d-grid gap-2">
        <%= link_to 'Editar', edit_training_path(@training), class: 'btn btn-secondary' %>
        <%= link_to 'Eliminar', @training, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' %>
        <%= link_to 'Volver', trainings_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>