config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'personal_informations#edit'
  resources :users do
    resource :personal_information, only: [:show, :edit, :update, :create]  # Singular resource as each user has one personal information
  end
  resources :warm_ups
  resources :personal_informations
  resources :kinesiologist_details
  resources :personal_trainer_details
  resources :trainings

  resources :videos  # Agregar esta línea para los videos

end

app/models/warm_up.rb
class WarmUp < ApplicationRecord
    belongs_to :training
    has_many_attached :videos
    has_many :warm_up_videos
    has_many :videos, through: :warm_up_videos
    validates :exercise, presence: true
  
    def assign_videos(video_ids)
      self.video_ids = video_ids
    end
  end
  

app/controllers/warm_ups_controller.rb
class WarmUpsController < ApplicationController
  before_action :set_warm_up, only: %i[show edit update destroy]

  # GET /warm_ups
  def index
    trainings = current_user.trainings
    @warm_ups = WarmUp.includes(:videos).where(training_id: trainings.pluck(:id))
  end

  # GET /warm_ups/1
  def show
  end

  # GET /warm_ups/new
  def new
    @warm_up = WarmUp.new
    @trainings = current_user.trainings
    @videos = Video.all
  end

  # GET /warm_ups/1/edit
  def edit
    @trainings = current_user.trainings
    @videos = Video.all
  end

  # POST /warm_ups
  def create
    @warm_up = WarmUp.new(warm_up_params)
    @warm_up.assign_videos(params[:warm_up][:video_ids]) if params[:warm_up][:video_ids].present?
    if @warm_up.save
      redirect_to @warm_up, notice: 'Warm up was successfully created.'
    else
      @trainings = current_user.trainings
      @videos = Video.all
      render :new
    end
  end
  
  def update
    if @warm_up.update(warm_up_params)
      redirect_to @warm_up, notice: 'Warm up was successfully updated.'
    else
      @trainings = current_user.trainings
      @videos = Video.all
      render :edit
    end
  end

  # DELETE /warm_ups/1
  def destroy
    @warm_up.destroy
    redirect_to warm_ups_url, notice: 'Warm up was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_warm_up
    @warm_up = WarmUp.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def warm_up_params
    params.require(:warm_up).permit(:exercise, :training_id, { video_ids: [] }, :video)
  end
end

app/helpers/warm_ups_helper.rb
module WarmUpsHelper
end

app/views/warm_ups/_form.html.erb
<%= form_with model: @warm_up, local: true do |form| %>
  <div class="form-group mb-3">
    <%= form.label :exercise, 'Ejercicio' %>
    <%= form.text_field :exercise, class: "form-control", required: true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :training_id, 'Entrenamiento' %>
    <%= form.collection_select :training_id, @trainings, :id, :exercise, { prompt: 'Seleccione el ejercicio' }, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :video_ids, 'Videos Existentes' %>
    <%= form.collection_select :video_ids, @videos, :id, :title, {}, { multiple: true, class: "form-control" } %>
  </div>


  <%= form.submit "Guardar", class: "btn btn-primary" %>
<% end %>

app/views/warm_ups/edit.html.erb
<h1>Editar Calentamiento</h1>
<%= render 'form', warm_up: @warm_up %>
<%= link_to 'Volver', warm_ups_path, class: 'btn btn-secondary' %>

app/views/warm_ups/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calentamientos</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">

</head>
<body>
  <div class="container mt-4">
    <h1 class="fancy-title">Mis Calentamientos</h1>
    <%= link_to 'Nuevo calentamiento', new_warm_up_path, class: 'btn btn-primary mt-4' %>
    <p> </p>

    <div class="row">
      <% @warm_ups.each do |warm_up| %>
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-header bg-warning">
              <h5 class="card-title"><%= warm_up.exercise %></h5>
            </div>
            <div class="card-body">
              <p class="card-text">Usuario: <%= warm_up.training.user.username %></p>
              <!-- Mostrar información básica sobre el video si está presente -->
              <% if warm_up.videos.any? %>
                <p class="card-text">Videos:</p>
                <ul>
                  <% warm_up.videos.each do |video| %>
                    <li><%= video.title %></li>
                  <% end %>
                </ul>
              <% end %>
              <a href="<%= warm_up_path(warm_up) %>" class="btn btn-primary">Ver detalle</a>
              <a href="<%= edit_warm_up_path(warm_up) %>" class="btn btn-secondary">Editar</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/warm_ups/new.html.erb
<h1>Nuevo Calentamiento</h1>
<%= render 'form', warm_up: @warm_up %>
<%= link_to 'Volver', warm_ups_path, class: 'btn btn-secondary' %>

app/views/warm_ups/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h3 class="card-title mb-0"><%= @warm_up.exercise %></h3>
        </div>
        <div class="card-body">
          <h5 class="card-subtitle mb-2 text-muted">Entrenamiento: <%= @warm_up.training.exercise %></h5>
          <h5 class="card-subtitle mb-2 text-muted">Usuario: <%= @warm_up.training.user.username %></h5>

          <% if @warm_up.videos.present? %>
            <% @warm_up.videos.each do |video| %>
              <div class="embed-responsive embed-responsive-16by9 mt-3 mb-3">
                <video width="100%" height="500" controls>
                  <source src="<%= rails_blob_path(video.file) %>" type="video/mp4">
                  Tu navegador no soporta videos.
                </video>
              </div>
            <% end %>
          <% else %>
            <p>No hay videos adjuntos.</p>
          <% end %>

          <div class="btn-group d-flex justify-content-center mt-2" role="group" aria-label="Acciones">
            <%= link_to 'Editar', edit_warm_up_path(@warm_up), class: 'btn btn-warning' %>
            <%= link_to 'Eliminar', @warm_up, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' %>
            <%= link_to 'Volver', warm_ups_path, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>